"use client";

import { ChevronDown } from "lucide-react";
import { useState } from "react";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

const PREVIEW_CHARS = 280;

export function AiCommentaryCard({ comment }: { comment: string }) {
  const [expanded, setExpanded] = useState(false);
  const needsTruncation = comment.length > PREVIEW_CHARS;
  const visible =
    expanded || !needsTruncation
      ? comment
      : `${comment.slice(0, PREVIEW_CHARS).trimEnd()}…`;

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-base">AI commentary</CardTitle>
        <CardDescription>
          Generated by the scan engine for this URL.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col gap-2">
        <p className="whitespace-pre-wrap text-sm leading-relaxed text-foreground">
          {visible}
        </p>
        {needsTruncation ? (
          <button
            type="button"
            onClick={() => setExpanded((v) => !v)}
            className="inline-flex w-fit items-center gap-1 text-xs font-medium text-muted-foreground hover:text-foreground"
            aria-expanded={expanded}
          >
            {expanded ? "Show less" : "Show more"}
            <ChevronDown
              className={`h-3.5 w-3.5 transition-transform ${expanded ? "rotate-180" : ""}`}
              aria-hidden
            />
          </button>
        ) : null}
      </CardContent>
    </Card>
  );
}
